### ISSUE TITLE
Cargo配置代理

### ISSUE THREAD

**Issue by nange** [nange/blog#43]
Cargo在拉取依赖时，由于国内环境总所周知的原因，通常配置一个代理能够更加高效。

在`$HOME/.cargo`目录创建`config.toml`文件：
```sh
vim ~/.cargo/config.toml
```

添加如下内容：
```toml
[http]
proxy = "socks5://127.0.0.1:2080"  // 地址根据实际情况而定

```
